Add possibility to perform dimensionality reduction using Umap algorithm
mastodon-sc/mastodon-deep-lineage pull request #113
Opened 2024-08-14 10:41 UTC by stefanhahmann

Resolves #109

2024-08-20 11:04 UTC, stefanhahmann commented
@haesleinhuepf I added you as a reviewer to this PR, since you drafted the issue that it (partially) resovles: #113

While I am not expecting a code review from your side, a functional review would be interesting. Could also be a joint session, since getting the branch of the plugin to run within Mastodon may take some time.

2024-08-23 16:13 UTC, haesleinhuepf approved these changes
Hey @stefanhahmann ,

as discussed today, the functionality looks good to me. I made some minor suggestions about the documentation below. Furthermore, one request: If possible, could we rename "UMAP output dimenstion 0" to "UMAP 0" ? It's pretty standard to call it like this and the shorter, the better.

Otherwise great. Thanks for working on this!

Best,
Robert

2024-08-23 16:13 UTC, haesleinhuepf commented on doc/dimensionalityreduction/readme.md
> +* [Uniform Manifold Approximation Projection (UMAP)](https://umap-learn.readthedocs.io/en/latest/)
```suggestion
* [Uniform Manifold Approximation Projection (UMAP)](https://arxiv.org/abs/1802.03426)
* [UMAP Python implementation](https://umap-learn.readthedocs.io/en/latest/)
```

2024-08-23 16:13 UTC, haesleinhuepf commented on doc/dimensionalityreduction/readme.md
> +For getting more insights into your data, you can reduce the dimensionality of the measurements, using this algorithm:
```suggestion
For visualizing high-dimensional data, e.g. in two dimensions, potentially getting more insights into your data, you can reduce the dimensionality of the measurements, using this algorithm:
```

2024-08-23 16:13 UTC, haesleinhuepf commented on doc/dimensionalityreduction/readme.md
> +Next, select the feature + feature projections that should be dimensionality reduced.
```suggestion
Next, select the feature + feature projections that should be dimensionality reduced. Select only features which describe the phenotype (spot size, shape, speed, number of neighbors, etc.) and avoid selecting technical features (e.g. Spot ID). Only select positional features (centroid) if the position of cells within the image are descriptive for the phenotype.
```

Just some ideas how to guide users. If they cannot select Spot ID anyway, please remove it from the suggestion.

2024-08-26 11:28 UTC, maarzt requested changes
There are big problems that still need to be fixed.

2024-08-26 11:28 UTC, maarzt commented on src/main/java/org/mastodon/mamut/feature/dimensionalityreduction/umap/feature/AbstractUmapFeatureComputer.java
> +			index++;
The usage of this "index" field in the class is horribly error prone. PLEASE replace it with a vertexToRowId map!!!! (You can use `RefToIntMap` or something like that.)

2024-08-26 11:28 UTC, maarzt commented on src/main/java/org/mastodon/mamut/feature/dimensionalityreduction/umap/feature/AbstractUmapFeatureComputer.java
> +		for ( V vertex : getVertices() )
You are using a `Collection<V>` interface here. Don't assume that there is a particular iterations order for a `Collection` it's not guarantied.

2024-09-02 08:52 UTC, maarzt approved these changes
Some small remarks.

2024-09-02 08:52 UTC, maarzt commented on src/test/java/org/mastodon/mamut/feature/dimensionalityreduction/umap/util/StandardScalerTest.java
> +		assertArrayEquals( expected, array );
I would prefer if only one of the three columns has variance zero. To make sure the other columns are still treated correctly.

2024-09-02 08:52 UTC, maarzt commented on src/main/java/org/mastodon/mamut/feature/dimensionalityreduction/umap/util/StandardScaler.java
> +			matrix[ i ][ columnIndex ] = Double.isNaN( standardizedColumn[ i ] ) ? 0d : standardizedColumn[ i ]; // replace NaNs with 0
This line removes any NaN value in the matrix. I guess it is implemented like this on the assumption, that all NaN values originate from StatUtils.normalize when applied on a constant column. It is ok to make this assumption, but only if you assume that the input matrix has NaN. Which is also true in this code base. But please document, that the standardizeColumns method expects the input matrix/array to have no NaN values.

2024-09-02 08:52 UTC, maarzt commented on src/main/java/org/mastodon/mamut/feature/dimensionalityreduction/umap/util/StandardScaler.java
> +			matrix[ i ][ columnIndex ] = Double.isNaN( standardizedColumn[ i ] ) ? 0d : standardizedColumn[ i ]; // replace NaNs with 0
This line could benefit from a comment, like:
_StatUtils.normalize(...) will write NaN if a column has variance=0, it is important to replace this NaN values before computing the UMAP_

2024-09-02 10:05 UTC, merged